# Generated by Django 6.0 on 2025-12-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/%Y/%m/%d/'),
        ),
    ]
