# Generated by Django 6.0 on 2025-12-27 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officer_portal', '0002_chatmessage_attachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='attachment',
        ),
    ]
