# Generated by Django 6.0 on 2025-12-27 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer_portal', '0003_alter_chatmessage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='ai_uploads/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='query',
            field=models.TextField(blank=True, help_text="The officer's input query"),
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_no', models.CharField(help_text='Reference/Complaint Number', max_length=100)),
                ('justification', models.TextField(help_text='Reason for using AI')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
