# Generated by Django 6.0 on 2026-02-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer_portal', '0005_legaldraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(help_text='Unique Case ID used by AI', max_length=255, unique=True)),
                ('summary', models.TextField(blank=True, help_text='Running log/summary of the case', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cases',
                'managed': True,
            },
        ),
    ]
