# Generated by Django 6.0 on 2026-02-08 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer_portal', '0007_case_description_case_officer_case_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='officer_portal.case'),
        ),
    ]
