# Generated by Django 6.0 on 2026-02-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer_portal', '0010_evidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
